version: "3.3"
services:
  frontend:
    image: travel-next-app_frontend
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: next_c
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
